version: "1"
services:
  ubuntu-dev-env:
    image: ubuntu:latest
    container_name: ubuntu-dev-env
    volumes:
      - .:/root/startup.sh
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_ADMIN
    ports:
      - "3000:3000"
      - "5000:5000"
      - "8888:8888"
    entrypoint: 
      - tail
      - -f
      - /dev/null
  
  alpine-dev-env:
    image: alpine:latest
    container_name: alpine-dev-env
    volumes:
      - .:/root/startup.sh
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_ADMIN
    ports:
      - "3000:3000"
      - "5000:5000"
      - "8888:8888"
    entrypoint: 
      - tail
      - -f
      - /dev/null